#Library('',[])
#Library('Test02SharedLib', ['../src_shared/test02_shared.c'])
#Library('Test02SharedLib', ['test02_shared.c'] ,CPPPATH=['../include'])
#StaticLibrary('Test02SharedLib' ,Glob('*.c') ,CPPPATH=['../include'])
#Library('Test02SharedLib' ,Glob('*.c') ,CPPPATH=['../include'])

#Import('env')
Import('*')

#env.Library('Test02SharedLib' ,Glob('*.c') ,CPPPATH=['../include'])
#env.Library('Test02SharedLib' ,Glob('*.[s|c|cpp]') ,CPPPATH=['../include'])
#env.Library('Test02SharedLib' ,Glob('*.cpp') ,CPPPATH=['../include'])
#env.Library('Test02SharedLib' ,Glob('*.c*') ,CPPPATH=['../include'])
#env.Library('Test02SharedLib' ,Glob('*.c[cp]*') ,CPPPATH=['../include'])

#env.Library('Test02SharedLib' ,Glob('*.c[cp]*') ,CPPPATH=['../header'])
#env.StaticLibrary('Test02StaticSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['../header'])
env.SharedLibrary('Test02SharedSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['../header'])

#obj = env.Object([Glob('./src/*.c[cp]*')])
obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header'])
Return('obj')

#Program('',[])

#Program('test02' ,['../src/test02.c' ,CPPPATH=['../src' ,'../scr_shared' ,'../include'] ,['../src/say_hello_02.c'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['.'])
#Program('test02' ,['../src/test02.c' ,'../src/say_hello_02.c'] ,CPPPATH=['../include'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['.'])
#Program('test02' ,['../src/test02.c' ,'../src/say_hello_02.c'] ,CPPPATH=['../include'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['.'])
