#Library('',[])
#Library('Test02SharedLib', ['../src_shared/test02_shared.c'])
#Library('Test02SharedLib', ['../src_shared/test02_shared.c'] ,CPPPATH=['../include'])

#Program('',[])

Import("env")
Import("opt")
Import("dbg")

#
#env.Program('test02' ,Glob('./src/*.c[cp]*') ,CPPPATH=['./include' ,'./libs/shared/header' ,'./libs/say_hello/header' ,'./libs/practice/header'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['./libs/shared/src' ,'./libs/practice/src' ,'./libs/say_hello/src' ])

#obj = env.Object([Glob('./src/*.c[cp]*')])
#obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header'])
#obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header' ,'../libs/shared/header' ,'../libs/say_hello/header' ,'../libs/practice/header'])
obj = env.Object([Glob('./src/*.c[cp]*')]
                  ,CCFLAGS=''
                  ,CPPPATH=[
                            './header'
                            ,'../libs/shared/header'
                            ,'../libs/practice/header'
                            ,'../libs/say_hello/header'])
Return('obj')

#opt.Program('test02-opt' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['../src_shared'])
#dbg.Program('test02-dbg' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['../src_shared'])
