#Import('env')
Import('*')

#env.Library('Test03SharedLib' ,Glob('*.c[cp]*') ,CPPPATH=['../header'])
#env.StaticLibrary('Test03StaticSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['../header'])
env.SharedLibrary('Test03SharedSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['./header'])

#obj = env.Object([Glob('./src/*.c[cp]*')])
obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header'])
Return('obj')
