#Library('',[])
#Library('TestSharedLib', ['../src_shared/test_shared.c'])
#Library('TestSharedLib', ['../src_shared/test_shared.c'] ,CPPPATH=['../include'])

#Program('',[])

Import("env")
Import("opt")
Import("dbg")

#
#env.Program('test' ,Glob('./src/*.c[cp]*') ,CPPPATH=['./include' ,'./libs/shared/header' ,'./libs/say_hello/header' ,'./libs/practice/header'] ,LIBS=['TestSharedLib'] ,LIBPATH=['./libs/shared/src' ,'./libs/practice/src' ,'./libs/say_hello/src' ])

#obj = env.Object([Glob('./src/*.c[cp]*')])
#obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header'])
#obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header' ,'../libs/shared/header' ,'../libs/say_hello/header' ,'../libs/practice/header'])
obj = env.Object([Glob('./src/*.c[cp]*')]
                  ,CCFLAGS=''
                  ,CPPPATH=[
                              './header'
                            , '../libs_shared/shared/header'
                            , '../libs/practice/header'
                            , '../libs/say_hello/header'
                            ])
Return('obj')

#opt.Program('test-opt' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['TestSharedLib'] ,LIBPATH=['../src_shared'])
#dbg.Program('test-dbg' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['TestSharedLib'] ,LIBPATH=['../src_shared'])
