#!/bin/bash

# run like this

export Test02BuildPath="./build_cmake"
export Test02SourcePath="."

  #cmake3.13#cmake -B${Test13BuildPath} -S${Test13SourcePath}
  cmake -B${Test02BuildPath} -H${Test02SourcePath}
  cd ${Test02BuildPath}
  make clean
  make
  ./Test02
  cd -
