#good doc #https://scons.org/doc/production/HTML/scons-user.html#app-functions

#Library('',[])
#Library('Test02SharedLib', ['../src_shared/test02_shared.c'])
#Library('Test02SharedLib', ['../src_shared/test02_shared.c'] ,CPPPATH=['../include'])

#Program('',[])

#Program('test02' ,['../src/test02.c' ,CPPPATH=['../src' ,'../scr_shared' ,'../include'] ,['../src/say_hello_02.c'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['.'])
#Program('test02' ,['../src/test02.c' ,'../src/say_hello_02.c'] ,CPPPATH=['../include'] ,LIBS=['Test02SharedLib'] ,LIBPATH=['.'])

#SConstruct

#env = Environment(CC='gcc' ,CCFLAGS=' -O2 -Wall -g' ,CPPDEFINES=['MyDefine02'])
#
#env = Environment(CC='gcc')
#env = Environment(CXX='g++')
env = Environment(CC='clang')
env = Environment(CXX='clang++')
#env = Environment(CXX='clang++')
#env.Replace(CC='clang++')
#env.Append(CCFLAGS=' -Wall -g')
env.Append(CCFLAGS=' -O2 -Wall -g')
#
env.Prepend(CPPDEFINES=['MyFirstDefine00'])
env.Append(CPPDEFINES=['MyDefine02'])
env.Append(MyVariableAdded02=['MyVariableAdded02'])
print("MyVariableAdded02 = %s" % env['MyVariableAdded02'])
#
opt = env.Clone(CCFLAGS=[' -O2'])
dbg = env.Clone(CCFLAGS=[' -Wall -g'])
#
#env.Program('test02' ,['foo.c'])
#
#o = opt.Object('test02-o' ,['foo.c'])
#opt.Program(o)
##
#d = dbg.Object('test02-d' ,['foo.c'])
#dbg.Program(d)

Export ('env')
#Export ("opt", "dbg")
#Export ('opt dbg')
Export ('opt', 'dbg')
#Export ('dbg')

objs  = []
header_file_path  = []


#SConscript(['src_shared/SConscript']
#            , variant_dir='build_sc_shared'
#            , duplicate=False
#          )
#SConscript(['src/SConscript']
#            , variant_dir='build_sc'
#            , duplicate=False
#          )


#SConscript(['src/SConscript']
##            , variant_dir='build_sc'
#             , exports='env'
#          )
#SConscript(['./libs/shared/src/SConscript']
##            , variant_dir='build_sc_shared'
#             , exports='env'
#          )
#SConscript(['./libs/practice/src/SConscript']
##            , variant_dir='build_sc_shared'
#             , exports='env'
#          )
#SConscript(['./libs/say_hello/src/SConscript']
##            , variant_dir='build_sc_shared'
#             , exports='env'
#          )



#            , variant_dir='build_sc'

objs.append( SConscript(['./SConscript'] ,exports='env')                  )
objs.append( SConscript(['./libs/shared/SConscript'] , exports='env')   )
objs.append( SConscript(['./libs/practice/SConscript'] , exports='env')     )
objs.append( SConscript(['./libs/say_hello/SConscript'] , exports='env')    )

#env.Program('test02' , objs)
env.Program('test02' ,objs ,CPPPATH=['./include' ,'./libs/shared/header' ,'./libs/say_hello/header' ,'./libs/practice/header'])