#!/bin/bash

# run like this

if [ ! -d ./build_cmake ]; then
   mkdir build_cmake
fi

if [ -d ./build_cmake ]; then
  cd build_cmake
  #cmake -G "Unix Makefiles" ..
  cmake ..
  make clean
  make
  ./Test03
  cd -
#  mkdir build_cmake
fi
